% !Mode:: "TeX:UTF-8"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 
%% This is a template for SYSU student.
%%
%%========================================
%%
%% Author: ekli
%% e-mail: lekf123@163.com
%% version 0.1
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesClass{sysuthesis}[2021/03/27 v0.1 The LaTeX template for thesis of SYSU]
\typeout{Document Class `sysuthesis' v0.1 by ekli (2021/03/27)}